#ifndef __STRATA_ARCH_INTERRUPT_CONSTANTS_H__
#define __STRATA_ARCH_INTERRUPT_CONSTANTS_H__

#define USER_IRQ_VECTOR_BASE          0x20
#define USER_IRQ_VECTOR_LIMIT         0xFF

#endif // __STRATA_ARCH_INTERRUPT_CONSTANTS_H__
