#ifndef __STRATA_PLAT_GDT_CONSTANTS_H__
#define __STRATA_PLAT_GDT_CONSTANTS_H__

#define GDT_ENTRY_COUNT 7

#define SEG_SEL_KERNEL_CODE 0x08
#define SEG_SEL_KERNEL_DATA 0x10
#define SEG_SEL_USER_DATA   0x18
#define SEG_SEL_USER_CODE   0x20
#define SEG_SEL_TSS         0x28

#endif  // __STRATA_PLAT_GDT_CONSTANTS_H__
