#ifndef __STRATA_PLAT_INTERRUPT_CONSTANTS_H__
#define __STRATA_PLAT_INTERRUPT_CONSTANTS_H__

#define LEGACY_IRQ_VECTOR_BASE    0x20
#define LEGACY_IRQ_VECTOR_LIMIT   0x2F
#define HPET_IRQ_VECTOR           0x20
#define SYSCALL_COMPAT_IRQ_VECTOR 0x80
#define LAPIC_TIMER_IRQ_VECTOR    0xE0
#define SPURIOUS_IRQ_VECTOR       0xFF

#if HPET_IRQ_VECTOR == LEGACY_IRQ_VECTOR_BASE
#define TIMER_IRQ_VECTOR(use_hpet) HPET_IRQ_VECTOR
#else
#define TIMER_IRQ_VECTOR(use_hpet) ((use_hpet) ? HPET_IRQ_VECTOR : LEGACY_IRQ_VECTOR_BASE)
#endif

#endif  // __STRATA_PLAT_INTERRUPT_CONSTANTS_H__
