#ifndef __STRATA_PLAT_MEMMAP_H__
#define __STRATA_PLAT_MEMMAP_H__

#define MEMMAP_LOCAL_VPN_BASE  ((St_VirtPage)0x0000000000000ULL)
#define MEMMAP_LOCAL_VPN_LIMIT ((St_VirtPage)0x7FFFFFFFFFFFFULL)

#define MEMMAP_GLOBAL_VPN_BASE  ((St_VirtPage)0x8000000000000ULL)
#define MEMMAP_GLOBAL_VPN_LIMIT ((St_VirtPage)0xFFFFFFFFFFFFFULL)

#define MEMMAP_USER_VPN_BASE  ((St_VirtPage)0x0000000000200ULL)
#define MEMMAP_USER_VPN_LIMIT ((St_VirtPage)0x00007FFF7FFFFULL)

#define MEMMAP_KRT_VPN_BASE  ((St_VirtPage)0xFFFF800000000ULL)
#define MEMMAP_KRT_VPN_LIMIT ((St_VirtPage)0xFFFF80007FFFFULL)

#define MEMMAP_MODULE_VPN_BASE  ((St_VirtPage)0xFFFF800080000ULL)
#define MEMMAP_MODULE_VPN_LIMIT ((St_VirtPage)0xFFFFBFFF7FFFFULL)

#define MEMMAP_DIRECTMAP_VPN_BASE  ((St_VirtPage)0xFFFFC00000000ULL)
#define MEMMAP_DIRECTMAP_VPN_LIMIT ((St_VirtPage)0xFFFFC7FF7FFFFULL)

#define MEMMAP_MFMAREA_VPN_BASE  ((St_VirtPage)0xFFFFC80000000ULL)
#define MEMMAP_MFMAREA_VPN_LIMIT ((St_VirtPage)0xFFFFCFFFFFFFFULL)

#define MEMMAP_IO_VPN_BASE  ((St_VirtPage)0xFFFFF00000000ULL)
#define MEMMAP_IO_VPN_LIMIT ((St_VirtPage)0xFFFFF7FFFFFFFULL)

#define MEMMAP_KERNEL_SLOW_VPN_BASE  ((St_VirtPage)0xFFFFF80000000ULL)
#define MEMMAP_KERNEL_SLOW_VPN_LIMIT ((St_VirtPage)0xFFFFFFFEFFFFFULL)

#define MEMMAP_KERNEL_FAST_VPN_BASE  ((St_VirtPage)0xFFFFFFFF80000ULL)
#define MEMMAP_KERNEL_FAST_VPN_LIMIT ((St_VirtPage)0xFFFFFFFFFFFFFULL)

#define IS_GLOBAL_VPN(vpn) ((vpn) >= MEMMAP_GLOBAL_VPN_BASE)
#define IS_LOCAL_VPN(vpn)  ((vpn) <= MEMMAP_LOCAL_VPN_LIMIT)

#endif  // __STRATA_PLAT_MEMMAP_H__
