#ifndef __STRATA_PLAT_MEMMAP_H__
#define __STRATA_PLAT_MEMMAP_H__

#include <strata/arch/mmu_constants.h>

/*
 * Keep base/limit addresses free of C casts so preprocessed linker scripts can
 * share the same layout constants. VPN aliases below preserve the C-facing API.
 */

#define MEMMAP_LOCAL_ADDR_BASE  0x0000000000000000
#define MEMMAP_LOCAL_ADDR_LIMIT 0x7FFFFFFFFFFFFFFF

#define MEMMAP_GLOBAL_ADDR_BASE  0x8000000000000000
#define MEMMAP_GLOBAL_ADDR_LIMIT 0xFFFFFFFFFFFFFFFF

#define MEMMAP_USER_ADDR_BASE  0x0000000000200000
#define MEMMAP_USER_ADDR_LIMIT 0x00007FFF7FFFFFFF

#define MEMMAP_KRT_DATA_ADDR_BASE  0x00007FFF80000000
#define MEMMAP_KRT_DATA_ADDR_LIMIT 0x00007FFFFFFFFFFF

#define MEMMAP_KRT_TEXT_ADDR_BASE  0xFFFF800000000000
#define MEMMAP_KRT_TEXT_ADDR_LIMIT 0xFFFF80007FFFFFFF

#define MEMMAP_MODULE_ADDR_BASE  0xFFFF800080000000
#define MEMMAP_MODULE_ADDR_LIMIT 0xFFFFBFFF7FFFFFFF

#define MEMMAP_DIRECTMAP_ADDR_BASE  0xFFFFC00000000000
#define MEMMAP_DIRECTMAP_ADDR_LIMIT 0xFFFFC7FF7FFFFFFF

#define MEMMAP_MFMAREA_ADDR_BASE  0xFFFFC80000000000
#define MEMMAP_MFMAREA_ADDR_LIMIT 0xFFFFCFFFFFFFFFFF

#define MEMMAP_IO_ADDR_BASE  0xFFFFF00000000000
#define MEMMAP_IO_ADDR_LIMIT 0xFFFFF7FFFFFFFFFF

#define MEMMAP_KERNEL_SLOW_ADDR_BASE  0xFFFFF80000000000
#define MEMMAP_KERNEL_SLOW_ADDR_LIMIT 0xFFFFFFFEFFFFFFFF

#define MEMMAP_KERNEL_FAST_ADDR_BASE  0xFFFFFFFF80000000
#define MEMMAP_KERNEL_FAST_ADDR_LIMIT 0xFFFFFFFFFFFFFFFF

#define MEMMAP_LOCAL_VPN_BASE  ((St_VirtPage)(MEMMAP_LOCAL_ADDR_BASE / PAGE_SIZE))
#define MEMMAP_LOCAL_VPN_LIMIT ((St_VirtPage)(MEMMAP_LOCAL_ADDR_LIMIT / PAGE_SIZE))

#define MEMMAP_GLOBAL_VPN_BASE  ((St_VirtPage)(MEMMAP_GLOBAL_ADDR_BASE / PAGE_SIZE))
#define MEMMAP_GLOBAL_VPN_LIMIT ((St_VirtPage)(MEMMAP_GLOBAL_ADDR_LIMIT / PAGE_SIZE))

#define MEMMAP_USER_VPN_BASE  ((St_VirtPage)(MEMMAP_USER_ADDR_BASE / PAGE_SIZE))
#define MEMMAP_USER_VPN_LIMIT ((St_VirtPage)(MEMMAP_USER_ADDR_LIMIT / PAGE_SIZE))

#define MEMMAP_KRT_DATA_VPN_BASE  ((St_VirtPage)(MEMMAP_KRT_DATA_ADDR_BASE / PAGE_SIZE))
#define MEMMAP_KRT_DATA_VPN_LIMIT ((St_VirtPage)(MEMMAP_KRT_DATA_ADDR_LIMIT / PAGE_SIZE))

#define MEMMAP_KRT_TEXT_VPN_BASE  ((St_VirtPage)(MEMMAP_KRT_TEXT_ADDR_BASE / PAGE_SIZE))
#define MEMMAP_KRT_TEXT_VPN_LIMIT ((St_VirtPage)(MEMMAP_KRT_TEXT_ADDR_LIMIT / PAGE_SIZE))

#define MEMMAP_KRT_VPN_BASE  MEMMAP_KRT_TEXT_VPN_BASE
#define MEMMAP_KRT_VPN_LIMIT MEMMAP_KRT_TEXT_VPN_LIMIT

#define MEMMAP_MODULE_VPN_BASE  ((St_VirtPage)(MEMMAP_MODULE_ADDR_BASE / PAGE_SIZE))
#define MEMMAP_MODULE_VPN_LIMIT ((St_VirtPage)(MEMMAP_MODULE_ADDR_LIMIT / PAGE_SIZE))

#define MEMMAP_DIRECTMAP_VPN_BASE  ((St_VirtPage)(MEMMAP_DIRECTMAP_ADDR_BASE / PAGE_SIZE))
#define MEMMAP_DIRECTMAP_VPN_LIMIT ((St_VirtPage)(MEMMAP_DIRECTMAP_ADDR_LIMIT / PAGE_SIZE))

#define MEMMAP_MFMAREA_VPN_BASE  ((St_VirtPage)(MEMMAP_MFMAREA_ADDR_BASE / PAGE_SIZE))
#define MEMMAP_MFMAREA_VPN_LIMIT ((St_VirtPage)(MEMMAP_MFMAREA_ADDR_LIMIT / PAGE_SIZE))

#define MEMMAP_IO_VPN_BASE  ((St_VirtPage)(MEMMAP_IO_ADDR_BASE / PAGE_SIZE))
#define MEMMAP_IO_VPN_LIMIT ((St_VirtPage)(MEMMAP_IO_ADDR_LIMIT / PAGE_SIZE))

#define MEMMAP_KERNEL_SLOW_VPN_BASE  ((St_VirtPage)(MEMMAP_KERNEL_SLOW_ADDR_BASE / PAGE_SIZE))
#define MEMMAP_KERNEL_SLOW_VPN_LIMIT ((St_VirtPage)(MEMMAP_KERNEL_SLOW_ADDR_LIMIT / PAGE_SIZE))

#define MEMMAP_KERNEL_FAST_VPN_BASE  ((St_VirtPage)(MEMMAP_KERNEL_FAST_ADDR_BASE / PAGE_SIZE))
#define MEMMAP_KERNEL_FAST_VPN_LIMIT ((St_VirtPage)(MEMMAP_KERNEL_FAST_ADDR_LIMIT / PAGE_SIZE))

#define IS_GLOBAL_VPN(vpn) ((vpn) >= MEMMAP_GLOBAL_VPN_BASE)
#define IS_LOCAL_VPN(vpn)  ((vpn) <= MEMMAP_LOCAL_VPN_LIMIT)

#endif  // __STRATA_PLAT_MEMMAP_H__
