#ifndef __VELLUM_PLAT_GDT_CONSTANTS_H__
#define __VELLUM_PLAT_GDT_CONSTANTS_H__

#define GDT_ENTRY_COUNT 5

#define SEG_SEL_CODE32 0x08
#define SEG_SEL_DATA32 0x10
#define SEG_SEL_CODE16 0x18
#define SEG_SEL_DATA16 0x20

#endif  // __VELLUM_PLAT_GDT_CONSTANTS_H__
