#ifndef __STRATA_PCI_CFGSPACE_H__
#define __STRATA_PCI_CFGSPACE_H__

#include <stdint.h>

#define PCI_CFGHDR_VENDORID        0x00
#define PCI_CFGHDR_DEVICEID        0x02
#define PCI_CFGHDR_COMMAND         0x04
#define PCI_CFGHDR_STATUS          0x06
#define PCI_CFGHDR_REV_ID          0x08
#define PCI_CFGHDR_INTERFACE       0x09
#define PCI_CFGHDR_SUB_CLASS       0x0A
#define PCI_CFGHDR_BASE_CLASS      0x0B
#define PCI_CFGHDR_CACHE_LINE_SIZE 0x0C
#define PCI_CFGHDR_LATENCY_TIMER   0x0D
#define PCI_CFGHDR_HEADER_TYPE     0x0E
#define PCI_CFGHDR_BIST            0x0F

#define PCI_HEADER_TYPE_TYPE_GENERIC 0x00
#define PCI_HEADER_TYPE_TYPE_PCI2PCI 0x01
#define PCI_HEADER_TYPE_TYPE_PCI2CB  0x02
#define PCI_HEADER_TYPE_TYPE_MASK    0x7F
#define PCI_HEADER_TYPE_MULTIFUNC    0x80

#define PCI_BIST_COMPLETION_CODE_MASK  0x0F
#define PCI_BIST_COMPLETION_CODE_SHIFT 0
#define PCI_BIST_START                 0x40
#define PCI_BIST_CAPABLE               0x80

/* header type 0 (generic device) */
#define PCI_CFGHDR0_BAR0              0x10
#define PCI_CFGHDR0_BAR1              0x14
#define PCI_CFGHDR0_BAR2              0x18
#define PCI_CFGHDR0_BAR3              0x1C
#define PCI_CFGHDR0_BAR4              0x20
#define PCI_CFGHDR0_BAR5              0x24
#define PCI_CFGHDR0_CARDBUS_CIS_PTR   0x28
#define PCI_CFGHDR0_SUBSYS_VENDOR_ID  0x2C
#define PCI_CFGHDR0_SUBSYS_ID         0x2E
#define PCI_CFGHDR0_EXP_ROM_BASE_ADDR 0x30
#define PCI_CFGHDR0_CAPABILITIES_PTR  0x34
#define PCI_CFGHDR0_INTERRUPT_LINE    0x3C
#define PCI_CFGHDR0_INTERRUPT_PIN     0x3D
#define PCI_CFGHDR0_MIN_GNT           0x3E
#define PCI_CFGHDR0_MAX_LATENCY       0x3F

/* header type 1 (PCI-to-PCI bridge) */
#define PCI_CFGHDR1_BAR0                 0x10
#define PCI_CFGHDR1_BAR1                 0x14
#define PCI_CFGHDR1_PRIMARY_BUS          0x18
#define PCI_CFGHDR1_SECONDARY_BUS        0x19
#define PCI_CFGHDR1_SUBORDINATE_BUS      0x1A
#define PCI_CFGHDR1_SEC_LATENCY_TIMER    0x1B
#define PCI_CFGHDR1_IO_BASE              0x1C
#define PCI_CFGHDR1_IO_LIMIT             0x1D
#define PCI_CFGHDR1_SECONDARY_STATUS     0x1E
#define PCI_CFGHDR1_MEM_BASE             0x20
#define PCI_CFGHDR1_MEM_LIMIT            0x22
#define PCI_CFGHDR1_PREF_MEM_BASE        0x24
#define PCI_CFGHDR1_PREF_MEM_LIMIT       0x26
#define PCI_CFGHDR1_PREF_MEM_BASE_UPPER  0x28
#define PCI_CFGHDR1_PREF_MEM_LIMIT_UPPER 0x2C
#define PCI_CFGHDR1_IO_BASE_UPPER        0x30
#define PCI_CFGHDR1_IO_LIMIT_UPPER       0x32
#define PCI_CFGHDR1_CAPABILITIES_PTR     0x34
#define PCI_CFGHDR1_EXP_ROM_BASE_ADDR    0x38
#define PCI_CFGHDR1_INTERRUPT_LINE       0x3C
#define PCI_CFGHDR1_INTERRUPT_PIN        0x3D
#define PCI_CFGHDR1_BRIDGE_CONTROL       0x3E

/* header type 2 (PCi-to-CardBus bridge) */
#define PCI_CFGHDR2_SOCKET_BASE_ADDR 0x10
#define PCI_CFGHDR2_CAPABILITIES_PTR 0x14
#define PCI_CFGHDR2_SECONDARY_STATUS 0x16
#define PCI_CFGHDR2_PCI_BUS          0x18
#define PCI_CFGHDR2_CB_BUS           0x19
#define PCI_CFGHDR2_SUBORDINATE_BUS  0x1A
#define PCI_CFGHDR2_CB_LATENCY_TIMER 0x1B
#define PCI_CFGHDR2_MEM_BASE0        0x1C
#define PCI_CFGHDR2_MEM_LIMIT0       0x20
#define PCI_CFGHDR2_MEM_BASE1        0x24
#define PCI_CFGHDR2_MEM_LIMIT1       0x28
#define PCI_CFGHDR2_IO_BASE0         0x2C
#define PCI_CFGHDR2_IO_LIMIT0        0x30
#define PCI_CFGHDR2_IO_BASE1         0x34
#define PCI_CFGHDR2_IO_LIMIT1        0x38
#define PCI_CFGHDR2_INTERRUPT_LINE   0x3C
#define PCI_CFGHDR2_INTERRUPT_PIN    0x3D
#define PCI_CFGHDR2_BRIDGE_CONTROL   0x3E
#define PCI_CFGHDR2_SUBSYS_DEVICE_ID 0x40
#define PCI_CFGHDR2_SUBSYS_VENDOR_ID 0x42
#define PCI_CFGHDR2_LEGACY_MODE_BASE 0x44

#define PCI_COMMAND_INT_DISABLE       0x0400
#define PCI_COMMAND_FAST_B2B_ENABLE   0x0200
#define PCI_COMMAND_SERR_ENABLE       0x0100
#define PCI_COMMAND_PARITY_ERROR_RESP 0x0040
#define PCI_COMMAND_VGA_PALETTE_SNOOP 0x0020
#define PCI_COMMAND_MEM_WRITE_IVD_ENA 0x0010
#define PCI_COMMAND_SPECIAL_CYCLES    0x0008
#define PCI_COMMAND_BUS_MASTER        0x0004
#define PCI_COMMAND_MEMORY_SPACE      0x0002
#define PCI_COMMAND_IO_SPACE          0x0001

#define PCI_STATUS_PARITY_ERROR_DET  0x8000
#define PCI_STATUS_SYSTEM_ERROR_SIG  0x4000
#define PCI_STATUS_MASTER_ABORT_RECV 0x2000
#define PCI_STATUS_TARGET_ABORT_RECV 0x1000
#define PCI_STATUS_TARGET_ABORT_SIG  0x0800
#define PCI_STATUS_DEVSEL_TIMING     0x0600
#define PCI_STATUS_MASTER_PARITY_ERR 0x0100
#define PCI_STATUS_FAST_B2B_CAPABLE  0x0080
#define PCI_STATUS_66MHZ_CAPABE      0x0020
#define PCI_STATUS_CAPABILITIES_LIST 0x0010
#define PCI_STATUS_INTERRUPT_STATUS  0x0008

#define PCI_BAR_IOSPACE_SEL 0x00000001

#define PCI_BAR_MEM_TYPE_MASK     0x00000006
#define PCI_BAR_MEM_PREFETCH_MASK 0x00000008
#define PCI_BAR_MEM_BASE_MASK     0xFFFFFFF0

#define PCI_BAR_IO_BASE_MASK 0xFFFFFFFC

#endif  // __STRATA_PCI_CFGSPACE_H__
