#!/usr/bin/env python3
import argparse
import pathlib
import re
import subprocess
import sys


SYMBOL_MAGIC = 0x53594D53
SYMBOL_TYPES = {"T", "t", "W", "w"}


def run(cmd):
    subprocess.run(cmd, check=True)


def find_output_arg(cmd):
    for index, arg in enumerate(cmd):
        if arg == "-o":
            if index + 1 >= len(cmd):
                raise RuntimeError("link command has -o without an output path")
            return index, cmd[index + 1]
        if arg.startswith("-o") and len(arg) > 2:
            return index, arg[2:]
    raise RuntimeError("link command has no -o output path")


def replace_output(cmd, output):
    index, _ = find_output_arg(cmd)
    replaced = list(cmd)
    if replaced[index] == "-o":
        replaced[index + 1] = output
    else:
        replaced[index] = "-o" + output
    return replaced


def insert_object_before_output(cmd, obj):
    index, _ = find_output_arg(cmd)
    linked = list(cmd)
    linked.insert(index, obj)
    return linked


def symbol_priority(symbol_type, name):
    priority = 0
    if symbol_type.isupper():
        priority += 4
    if not name.startswith("."):
        priority += 2
    if not name.startswith("_"):
        priority += 1
    return priority


def read_symbols(nm, elf):
    line_re = re.compile(r"^([0-9A-Fa-f]+)\s+([A-Za-z])\s+(.+)$")
    completed = subprocess.run([nm, "-n", "--defined-only", elf], check=True, text=True, capture_output=True)
    by_addr = {}

    for line in completed.stdout.splitlines():
        match = line_re.match(line.strip())
        if not match:
            continue

        addr_s, symbol_type, name = match.groups()
        if symbol_type not in SYMBOL_TYPES:
            continue
        if not name:
            continue

        address = int(addr_s, 16)
        previous = by_addr.get(address)
        current = (symbol_priority(symbol_type, name), symbol_type, name)
        if previous is None or current > previous:
            by_addr[address] = current

    return [(address, data[2]) for address, data in sorted(by_addr.items())]


def asm_string(value):
    out = ['"']
    for byte in value.encode("utf-8"):
        ch = chr(byte)
        if ch == "\\":
            out.append("\\\\")
        elif ch == '"':
            out.append('\\"')
        elif 0x20 <= byte <= 0x7E:
            out.append(ch)
        else:
            out.append(f"\\{byte:03o}")
    out.append('"')
    return "".join(out)


def write_symbols_asm(path, symbols):
    names = bytearray(b"\0")
    offsets = []
    for _, name in symbols:
        offsets.append(len(names))
        names.extend(name.encode("utf-8"))
        names.append(0)

    with open(path, "w", encoding="utf-8") as f:
        f.write("/* Generated by tools/symbol_info/link_with_symbol_info.py. */\n")
        f.write("    .section .rodata.stsymbol,\"a\",@progbits\n")
        f.write("    .balign 8\n")

        f.write("    .globl StSymbolP_StaticMagic\n")
        f.write("    .type StSymbolP_StaticMagic, @object\n")
        f.write("StSymbolP_StaticMagic:\n")
        f.write(f"    .long 0x{SYMBOL_MAGIC:08X}\n")
        f.write("    .size StSymbolP_StaticMagic, . - StSymbolP_StaticMagic\n\n")

        f.write("    .balign 8\n")
        f.write("    .globl StSymbolP_StaticCount\n")
        f.write("    .type StSymbolP_StaticCount, @object\n")
        f.write("StSymbolP_StaticCount:\n")
        f.write(f"    .quad {len(symbols)}\n")
        f.write("    .size StSymbolP_StaticCount, . - StSymbolP_StaticCount\n\n")

        f.write("    .globl StSymbolP_StaticNamesSize\n")
        f.write("    .type StSymbolP_StaticNamesSize, @object\n")
        f.write("StSymbolP_StaticNamesSize:\n")
        f.write(f"    .quad {len(names)}\n")
        f.write("    .size StSymbolP_StaticNamesSize, . - StSymbolP_StaticNamesSize\n\n")

        f.write("    .balign 8\n")
        f.write("    .globl StSymbolP_StaticEntries\n")
        f.write("    .type StSymbolP_StaticEntries, @object\n")
        f.write("StSymbolP_StaticEntries:\n")
        for (address, _), offset in zip(symbols, offsets):
            f.write(f"    .quad 0x{address:016X}\n")
            f.write(f"    .long {offset}\n")
            f.write("    .long 0\n")
        f.write("    .size StSymbolP_StaticEntries, . - StSymbolP_StaticEntries\n\n")

        f.write("    .globl StSymbolP_StaticNames\n")
        f.write("    .type StSymbolP_StaticNames, @object\n")
        f.write("StSymbolP_StaticNames:\n")
        f.write("    .byte 0\n")
        for _, name in symbols:
            f.write(f"    .asciz {asm_string(name)}\n")
        f.write("    .size StSymbolP_StaticNames, . - StSymbolP_StaticNames\n")


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--nm", required=True)
    parser.add_argument("--cc", required=True)
    parser.add_argument("command", nargs=argparse.REMAINDER)
    args = parser.parse_args()

    command = args.command
    if command and command[0] == "--":
        command = command[1:]
    if not command:
        raise RuntimeError("missing wrapped link command")

    _, target = find_output_arg(command)
    target_path = pathlib.Path(target)
    unsym = str(target_path.with_suffix(target_path.suffix + ".unsym"))
    symbol_info_s = str(target_path.with_suffix(target_path.suffix + ".symbol_info.S"))
    symbol_info_o = str(target_path.with_suffix(target_path.suffix + ".symbol_info.o"))

    run(replace_output(command, unsym))

    symbols = read_symbols(args.nm, unsym)
    write_symbols_asm(symbol_info_s, symbols)

    run([args.cc, "-c", symbol_info_s, "-o", symbol_info_o])
    run(insert_object_before_output(command, symbol_info_o))


if __name__ == "__main__":
    try:
        main()
    except Exception as exc:
        print(f"link_with_symbol_info.py: {exc}", file=sys.stderr)
        sys.exit(1)
