name: Build

on:
  push:
    branches: [ "main", "github-actions" ]
  pull_request:
    branches: [ "main", "github-actions" ]

jobs:
  build:
    runs-on: macos-latest
    strategy:
      matrix:
        target: [amd64-pc-bios]

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Install dependencies
      run: |
        brew update
        brew install i686-elf-gcc i686-elf-binutils x86_64-elf-gcc x86_64-elf-binutils cmake ninja mtools

    - name: Configure CMake
      # Using -B build to specify build directory
      run: cmake -B build -G Ninja -DTARGET=${{ matrix.target }}

    - name: Build
      run: cmake --build build

    - name: Create Disk Image
      run: |
        # Ensure scripts are executable
        chmod +x scripts/mkdisk.sh
        scripts/mkdisk.sh -a ia32 disk.img

    - name: Upload Disk Image
      uses: actions/upload-artifact@v4
      with:
        name: disk.img
        path: disk.img
        if-no-files-found: error

  build-linux:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target: [ amd64-pc-bios ]
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Cache Toolchain
        id: cache-toolchain
        uses: actions/cache@v4
        with:
          path: ~/opt/cross
          key: toolchain-${{ runner.os }}-${{ hashFiles('scripts/build_toolchain.sh') }}

      - name: Build Toolchain
        if: steps.cache-toolchain.outputs.cache-hit != 'true'
        run: |
          chmod +x scripts/build_toolchain.sh
          scripts/build_toolchain.sh

      - name: Add Toolchain to PATH
        run: echo "$HOME/opt/cross/bin" >> $GITHUB_PATH

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake ninja-build python3 mtools uuid-runtime gdisk bison flex libgmp3-dev libmpc-dev libmpfr-dev texinfo

      - name: Build
        run: |
          mkdir -p build && cd build
          cmake .. -G Ninja -DTARGET=${{ matrix.target }}
          ninja

      - name: Create Disk Image
        run: |
          chmod +x scripts/mkdisk.sh
          scripts/mkdisk.sh -a ia32 disk.img

      - name: Upload Disk Image
        uses: actions/upload-artifact@v4
        with:
          name: linux-${{ matrix.target }}-disk.img
          path: disk.img
          retention-days: 3
          if-no-files-found: error
